name: Repo creation

on: workflow_dispatch

jobs:
  create_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Create repo steps
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_OWNER: ${{ vars.GH_OWNER }}
          GH_USER_CREATOR: ${{ github.actor }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: yarn health-check
