name: Health check

on: workflow_dispatch

jobs:
  health_check:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check out github repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Health check steps
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_OWNER: ${{ vars.GH_OWNER }}
          GH_USER_CREATOR: ${{ github.actor }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: yarn health-check
