name: Repo creation

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Repository name"
        required: true
      repo_codeowner:
        description: "Codeowners (eg. @defi-wonderland/default-codeowner) or empty for default"
        required: false
      template:
        description: "Template (eg. defi-wonderland/solidity-hardhat-boilerplate) or empty if not from template"
        required: false

jobs:
  create_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Create repo steps
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_OWNER: ${{ vars.GH_OWNER }}
          GH_REPO_NAME: ${{ github.event.inputs.repo_name }}
          GH_USER_CREATOR: ${{ github.actor }}
          GH_CODEOWNER: ${{ github.event.inputs.repo_codeowner }}
          GH_TEMPLATE: ${{ github.event.inputs.template }}
          DISCORD_CHANNEL: ${{ secrets.DISCORD_CHANNEL }}
        run: yarn create-repo
