name: Repo creation

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Repository name"
        required: true
      repo_codeowner:
        description: "Codeowners (eg: @defi-wonderland/price-solidity-codeowners)"
        required: false
      from_template_owner:
        description: "Template owner (eg. defi-wonderland)"
        required: false
      from_template_repo:
        description: "Template repo (eg. solidity-hardhat-boilerplate)"
        required: false

jobs:
  create_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Create repo steps
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_OWNER: ${{ vars.GH_OWNER }}
          GH_REPO_NAME: ${{ github.event.inputs.repo_name }}
          GH_USER_CREATOR: ${{ github.actor }}
          GH_CODEOWNER: ${{ github.event.inputs.repo_codeowner }}
          GH_TEMPLATE_OWNER: ${{ github.event.inputs.from_template_owner }}
          GH_TEMPLATE_REPO: ${{ github.event.inputs.from_template_repo }}
        run: yarn create-repo
